CREATE TABLE IF NOT EXISTS Product(
id VARCHAR(25) NOT NULL,
name VARCHAR(100),
nova VARCHAR(5),
category VARCHAR(30),
brand TEXT,
stores VARCHAR(120),
PRIMARY KEY (id)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Favourites(
no VARCHAR(20),
sub TEXT,
CONSTRAINT fk_Product_no
FOREIGN KEY (no)
REFERENCES Product(id)
)
ENGINE = InnoDB;